"use client";
import { useState } from "react";
type Variant = { id:string; sku:string; price:number|string; stockQuantity:number; attributesJson:Record<string,string> };
type Product = { id:string; title:string; slug:string; description:string; isPublished:boolean; imageUrl:string|null; categoryId:string|null; category:{name:string}|null; variants:Variant[] };
type Settings = { gatewayEnabled:boolean; activePaymentProviders:string[]; shippingFee:number; lowStockThreshold:number; storeName:string; currency:string };
type Props = { products:Product[]; orders:{id:string;orderNumber:string;customerName:string;totalAmount:number|string;status:string;paymentStatus:string;createdAt:string}[]; logs:{id:string;changeQuantity:number;reason:string;createdAt:string;variant:{sku:string;product:{title:string}}}[]; settings:Settings };
const providers=["cod","bank_transfer","order_request","stripe","paypal"];
export function AdminPanel({ products:initial, orders, logs:initialLogs, settings:initialSettings }:Props) {
 const [products,setProducts]=useState(initial); const [logs,setLogs]=useState(initialLogs); const [settings,setSettings]=useState({...initialSettings,shippingFee:Number(initialSettings.shippingFee)}); const [note,setNote]=useState(""); const [tab,setTab]=useState("inventory");
 async function request(url:string,method:string,body:unknown){const r=await fetch(url,{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error??"Request failed");return data;}
 async function adjust(form:FormData){setNote("");try{const data=await request("/api/admin/inventory","POST",{variantId:form.get("variantId"),changeQuantity:Number(form.get("changeQuantity")),reason:form.get("reason")});setProducts(products.map(p=>({...p,variants:p.variants.map(v=>v.id===form.get("variantId")?{...v,stockQuantity:data.stockQuantity}:v)})));setNote("Inventory updated.");window.location.reload();}catch(e){setNote(e instanceof Error?e.message:"Could not update inventory.");}}
 async function saveSettings(form:FormData){const next={...settings,storeName:String(form.get("storeName")),currency:String(form.get("currency")).toUpperCase(),shippingFee:Number(form.get("shippingFee")),lowStockThreshold:Number(form.get("lowStockThreshold")),gatewayEnabled:form.get("gatewayEnabled")==="on",activePaymentProviders:form.getAll("providers").map(String)};try{await request("/api/admin/settings","PUT",next);setSettings(next);setNote("Settings saved.");}catch(e){setNote(e instanceof Error?e.message:"Could not save settings.");}}
 async function createProduct(form:FormData){const title=String(form.get("title"));const attributesJson:Record<string,string>={};if(form.get("size"))attributesJson.Size=String(form.get("size"));if(form.get("color"))attributesJson.Color=String(form.get("color"));try{const created=await request("/api/admin/products","POST",{title,slug:String(form.get("slug")),description:String(form.get("description")),isPublished:form.get("isPublished")==="on",variants:[{sku:String(form.get("sku")),price:Number(form.get("price")),stockQuantity:Number(form.get("stockQuantity")),attributesJson}]});setProducts([created,...products]);setNote("Product created.");}catch(e){setNote(e instanceof Error?e.message:"Could not create product.");}}
 async function editProduct(product:Product){const title=window.prompt("Product title",product.title);if(!title)return;const description=window.prompt("Product description",product.description);if(description===null)return;try{await request(`/api/admin/products/${product.id}`,"PUT",{title,slug:product.slug,description,isPublished:product.isPublished,imageUrl:product.imageUrl??"",categoryId:product.categoryId});setProducts(products.map(p=>p.id===product.id?{...p,title,description}:p));setNote("Product details saved.");}catch(e){setNote(e instanceof Error?e.message:"Could not edit product.");}}
 async function toggleProduct(product:Product){try{await request(`/api/admin/products/${product.id}`,"PUT",{title:product.title,slug:product.slug,description:product.description,isPublished:!product.isPublished,imageUrl:product.imageUrl??"",categoryId:product.categoryId});setProducts(products.map(p=>p.id===product.id?{...p,isPublished:!p.isPublished}:p));}catch(e){setNote(e instanceof Error?e.message:"Could not update product.");}}
 return <div className="mt-10"><div className="flex flex-wrap gap-2 border-b border-black/10 pb-4">{[["inventory","Inventory"],["orders","Orders"],["products","Products"],["settings","Settings"],["activity","Stock activity"]].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`rounded-full px-4 py-2 text-sm ${tab===id?"bg-[#17231f] text-white":"border border-black/15"}`}>{label}</button>)}</div>{note&&<p className="my-4 rounded-xl bg-[#e7eddf] p-3 text-sm">{note}</p>}
 {tab==="inventory"&&<div className="mt-6 overflow-x-auto rounded-2xl bg-white"><table className="w-full text-left text-sm"><thead><tr className="border-b text-black/50"><th className="p-4">Product / variant</th><th className="p-4">SKU</th><th className="p-4">Price</th><th className="p-4">Stock</th><th className="p-4">Status</th></tr></thead><tbody>{products.flatMap(p=>p.variants.map(v=><tr key={v.id} className="border-b border-black/5"><td className="p-4 font-medium">{p.title}<div className="mt-1 text-xs font-normal text-black/40">{Object.values(v.attributesJson).join(" / ")||"Default option"}</div></td><td className="p-4">{v.sku}</td><td className="p-4">{settings.currency} {Number(v.price).toFixed(2)}</td><td className="p-4 font-semibold">{v.stockQuantity}</td><td className="p-4">{v.stockQuantity===0?<span className="text-red-700">Out of stock</span>:v.stockQuantity<=settings.lowStockThreshold?<span className="text-amber-700">Low stock</span>:"In stock"}</td></tr>))}</tbody></table><form action={adjust} className="flex flex-wrap items-end gap-3 border-t p-5"><label className="text-xs">Variant<select name="variantId" required className="mt-1 block rounded-lg border bg-white p-2">{products.flatMap(p=>p.variants.map(v=><option key={v.id} value={v.id}>{p.title} / {v.sku} ({v.stockQuantity})</option>))}</select></label><label className="text-xs">Change (+ restock / − reduce)<input name="changeQuantity" type="number" required className="mt-1 block w-40 rounded-lg border p-2"/></label><label className="text-xs">Reason<input name="reason" required minLength={3} placeholder="Restock delivery" className="mt-1 block rounded-lg border p-2"/></label><button className="rounded-full bg-[#17231f] px-4 py-2 text-sm text-white">Adjust stock</button></form></div>}
 {tab==="products"&&<div className="mt-6 grid gap-6 lg:grid-cols-[1fr_350px]"><div className="space-y-3">{products.map(p=><article key={p.id} className="flex items-center justify-between rounded-xl bg-white p-4"><div><p className="font-medium">{p.title}</p><p className="mt-1 text-xs text-black/50">/{p.slug} · {p.variants.length} variant(s)</p></div><div className="flex gap-2"><button onClick={()=>editProduct(p)} className="rounded-full border px-4 py-2 text-sm">Edit</button><button onClick={()=>toggleProduct(p)} className="rounded-full border px-4 py-2 text-sm">{p.isPublished?"Unpublish":"Publish"}</button></div></article>)}</div><form action={createProduct} className="space-y-3 rounded-2xl bg-white p-5"><h2 className="text-lg font-semibold">Add product</h2>{[["title","Title"],["slug","Slug (lowercase-with-dashes)"],["sku","Variant SKU"],["price","Price"],["stockQuantity","Starting stock"],["size","Size (optional)"],["color","Color (optional)"]].map(([name,label])=><label key={name} className="block text-xs">{label}<input name={name} required={!label.includes("(optional)")} className="mt-1 block w-full rounded-lg border p-2" type={name==="price"?"number":name==="stockQuantity"?"number":"text"} step={name==="price"?"0.01":undefined} min={name==="price"?"0.01":name==="stockQuantity"?"0":undefined}/></label>)}<label className="block text-xs">Description<textarea name="description" className="mt-1 block w-full rounded-lg border p-2"/></label><label className="flex gap-2 text-sm"><input name="isPublished" type="checkbox"/> Publish immediately</label><button className="rounded-full bg-[#17231f] px-4 py-2 text-sm text-white">Create product</button></form></div>}
 {tab==="orders"&&<div className="mt-6 overflow-x-auto rounded-2xl bg-white"><table className="w-full text-left text-sm"><thead><tr className="border-b text-black/50">{["Order","Customer","Total","Order status","Payment","Placed"].map(x=><th key={x} className="p-4">{x}</th>)}</tr></thead><tbody>{orders.map(o=><tr key={o.id} className="border-b border-black/5"><td className="p-4 font-medium">{o.orderNumber}</td><td className="p-4">{o.customerName}</td><td className="p-4">{settings.currency} {Number(o.totalAmount).toFixed(2)}</td><td className="p-4">{o.status}</td><td className="p-4">{o.paymentStatus}</td><td className="p-4">{new Date(o.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>}
 {tab==="settings"&&<form action={saveSettings} className="mt-6 grid max-w-3xl gap-5 rounded-2xl bg-white p-6 sm:grid-cols-2"><h2 className="text-xl font-semibold sm:col-span-2">Store settings</h2><label className="text-sm">Store name<input name="storeName" defaultValue={settings.storeName} className="mt-1 block w-full rounded-lg border p-3"/></label><label className="text-sm">Currency (ISO code)<input name="currency" defaultValue={settings.currency} maxLength={3} className="mt-1 block w-full rounded-lg border p-3"/></label><label className="text-sm">Shipping fee<input name="shippingFee" type="number" min="0" step="0.01" defaultValue={settings.shippingFee} className="mt-1 block w-full rounded-lg border p-3"/></label><label className="text-sm">Low stock threshold<input name="lowStockThreshold" type="number" min="0" defaultValue={settings.lowStockThreshold} className="mt-1 block w-full rounded-lg border p-3"/></label><label className="flex items-center gap-2 text-sm sm:col-span-2"><input name="gatewayEnabled" type="checkbox" defaultChecked={settings.gatewayEnabled}/> Enable online payment gateways</label><fieldset className="space-y-2 sm:col-span-2"><legend className="mb-2 text-sm font-medium">Active payment providers</legend>{providers.map(p=><label key={p} className="mr-5 inline-flex items-center gap-2 text-sm"><input name="providers" type="checkbox" value={p} defaultChecked={settings.activePaymentProviders.includes(p)}/>{({cod:"Cash on delivery",bank_transfer:"Bank transfer",order_request:"Order request",stripe:"Stripe",paypal:"PayPal"} as Record<string,string>)[p]}</label>)}</fieldset><button className="w-fit rounded-full bg-[#17231f] px-5 py-3 text-sm text-white">Save settings</button></form>}
 {tab==="activity"&&<div className="mt-6 space-y-3">{logs.map(log=><article key={log.id} className="flex flex-wrap justify-between gap-3 rounded-xl bg-white p-4 text-sm"><div><p className="font-medium">{log.variant.product.title} · {log.variant.sku}</p><p className="mt-1 text-black/50">{log.reason}</p></div><div className="text-right"><p className={log.changeQuantity>0?"text-[#496b50]":"text-amber-700"}>{log.changeQuantity>0?"+":""}{log.changeQuantity} units</p><p className="mt-1 text-xs text-black/40">{new Date(log.createdAt).toLocaleString()}</p></div></article>))}{!logs.length&&<p className="rounded-xl bg-white p-5 text-sm text-black/50">No stock activity yet.</p>}</div>}
 </div>;
}
