"use client";
import { useEffect, useState } from "react";
type CartItem = { variantId: string; quantity: number };
type CartRow = { id: string; sku: string; stockQuantity: number; price: number; attributesJson: Record<string, string>; product: { title: string } };
export function CheckoutForm({ providers, shippingFee, currency }: { providers: string[]; shippingFee: number; currency: string }) {
  const [cart, setCart] = useState<CartItem[]>([]); const [rows, setRows] = useState<CartRow[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [done, setDone] = useState("");
  useEffect(() => { const items = JSON.parse(localStorage.getItem("cart") ?? "[]") as CartItem[]; setCart(items); if (items.length) fetch("/api/cart", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ items }) }).then(r => r.json()).then(d => setRows(d.items ?? [])); }, []);
  async function submit(formData: FormData) { setError(""); setBusy(true); const address = { line1: String(formData.get("line1")), line2: String(formData.get("line2") ?? ""), city: String(formData.get("city")), region: String(formData.get("region")), postalCode: String(formData.get("postalCode")), country: String(formData.get("country")) }; const response = await fetch("/api/checkout", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ customerName: formData.get("name"), customerEmail: formData.get("email"), address, paymentMethod: formData.get("paymentMethod"), items: cart }) }); const result = await response.json(); setBusy(false); if (!response.ok) { setError(result.error ?? "Unable to submit your order."); return; } if (result.checkoutUrl) { window.location.assign(result.checkoutUrl); return; } localStorage.removeItem("cart"); setDone(result.orderNumber); }
  const subtotal = rows.reduce((total, row) => total + row.price * (cart.find(x => x.variantId === row.id)?.quantity ?? 0), 0);
  if (done) return <div className="mt-10 rounded-2xl bg-white p-8"><h2 className="text-2xl font-semibold">Thank you for your order</h2><p className="mt-3">Order reference: <strong>{done}</strong></p><p className="mt-2 text-black/60">We’ll be in touch with next steps.</p></div>;
  return <div className="mt-8 grid gap-10 md:grid-cols-[1fr_340px]"><form action={submit} className="space-y-8"><section className="rounded-2xl bg-white p-6"><h2 className="text-xl font-semibold">Contact and delivery</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{[["name","Full name"],["email","Email"],["line1","Street address"],["line2","Apartment (optional)"],["city","City"],["region","State / region"],["postalCode","Postal code"],["country","Country"]].map(([id,label])=><label key={id} className="text-sm">{label}<input name={id} required={!id.includes("line2")} className="mt-1 block w-full rounded-xl border border-black/15 px-3 py-3"/></label>)}</div></section><section className="rounded-2xl bg-white p-6"><h2 className="text-xl font-semibold">Payment</h2>{providers.length ? <div className="mt-4 space-y-3">{providers.map(p=><label key={p} className="flex items-center gap-3 rounded-xl border border-black/10 p-4 text-sm"><input type="radio" name="paymentMethod" value={p} required defaultChecked={providers[0]===p}/><span>{({cod:"Cash on delivery",bank_transfer:"Direct bank transfer",order_request:"Order request",stripe:"Credit / debit card",paypal:"PayPal"} as Record<string,string>)[p] ?? p}</span></label>)}</div> : <p className="mt-3 text-sm text-red-700">No payment methods are active. Contact the store.</p>}</section>{error && <p className="text-sm text-red-700">{error}</p>}<button disabled={busy || !cart.length} className="rounded-full bg-[#17231f] px-7 py-3 font-medium text-white disabled:opacity-40">{busy ? "Placing order…" : "Place order"}</button></form><aside className="h-fit rounded-2xl bg-white p-6"><h2 className="text-xl font-semibold">Summary</h2>{!cart.length && <p className="mt-4 text-sm text-black/50">Your cart is empty. <a href="/" className="underline">Browse the shop</a></p>}{rows.map(row=><div key={row.id} className="mt-5 flex justify-between gap-4 text-sm"><span>{row.product.title} × {cart.find(x=>x.variantId===row.id)?.quantity}{Object.values(row.attributesJson).length ? ` · ${Object.values(row.attributesJson).join(" / ")}` : ""}</span><span>{currency} {(row.price * (cart.find(x=>x.variantId===row.id)?.quantity ?? 0)).toFixed(2)}</span></div>)}<div className="mt-6 space-y-2 border-t pt-4 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{currency} {subtotal.toFixed(2)}</span></div><div className="flex justify-between"><span>Shipping</span><span>{currency} {shippingFee.toFixed(2)}</span></div><div className="flex justify-between pt-2 text-base font-semibold"><span>Total</span><span>{currency} {(subtotal + shippingFee).toFixed(2)}</span></div></div></aside></div>;
}
